# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Petal
version:      2.05
version_from: lib/Petal.pm
installdirs:  site
requires:
    MKDoc::XML:                    0.69
    Scalar::Util:                  1.07
    Test::Harness:                 2.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
