--- #YAML:1.0
name:               Petal
version:            2.20
abstract:           Perl Template Attribute Language - TAL for Perl!
author:
    - Jean-Michel Hiver
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:    
    MKDoc::XML:     0.72
    Scalar::Util:   1.07
    Test::Harness:  2.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
